.TH SWFDEC-PLAYER 1 "01 Nov 2007"
.SH NAME
swfdec-player \- Viewer for Flash files
.PP
.SH SYNOPSIS
.B swfdec-player
[ OPTION ...] <
.I FILE
> [<
.I FILE
> ...]

.SH DESCRIPTION
swfdec-player is a stand-alone viewer for Flash files. It is provided
to integrate Flash functionality into the GNOME desktop but can be used
outside of GNOME.

.SH HELP OPTIONS
.PP
.B -?\fR, \fB--help
Show help options
.PP
.B --help-all
Show all help options
.PP
.B --help-gtk
Show GTK+ Options

.SH APPLICATION OPTIONS
.PP
.B -n\fR, \fB--no-sound
don't play sound
.PP
.B -p\fR, \fB--paused
start player paused
.PP
.B --display=\fIDISPLAY
set X display to use

.SH SEE ALSO
.B swfdec-thumbnailer\fR(1), \fBhttp://swfdec.freedesktop.org

.SH AUTHOR
This manual page was written by Santiago Garcia Mantinan <manty@debian.org>.
